services:
  problem_seeder:
    build: .
    container_name: codescript-problems
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - PROBLEM_FILES_PATHS=${PROBLEM_FILES_PATHS}
      - IMAGE_FILES_PATHS=${IMAGE_FILES_PATHS}
    volumes:
      - .:/app
    networks:
      - codescript_network
    entrypoint: ["/entrypoint.sh"]

networks:
  codescript_network:
    external: true
