name: Post Problem and/or Upload Image

on:
  push:
    paths:
      - 'python/problems/**'
      - 'python/images/**'
    branches:
      - main  

jobs:
  detect_changes:
    runs-on: self-hosted
    outputs:
      problem_files_added: ${{ steps.set-env.outputs.problem_files_added }}
      image_files_added: ${{ steps.set-env.outputs.image_files_added }}
      problem_files_paths: ${{ steps.set-env.outputs.problem_files_paths }}
      image_files_paths: ${{ steps.set-env.outputs.image_files_paths }}

    steps:
      - name: Checkout codescript-problems
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Detect Added Files
        id: set-env
        run: |
          echo "📥 Fetching added files in the current repository..."
          ADDED_FILES=$(git diff --name-only --diff-filter=AMR ${{ github.event.before }} ${{ github.event.after }})
          echo "$ADDED_FILES"

          PROBLEM_FILES=$(echo "$ADDED_FILES" | grep "^python/problems/" || true)
          if [ -n "$PROBLEM_FILES" ]; then
            echo "problem_files_added=true" >> $GITHUB_OUTPUT
            echo "problem_files_paths=$(echo $PROBLEM_FILES | paste -sd "," -)" >> $GITHUB_OUTPUT
          fi

          IMAGE_FILES=$(echo "$ADDED_FILES" | grep "^python/images/" || true)
          if [ -n "$IMAGE_FILES" ]; then
            echo "image_files_added=true" >> $GITHUB_OUTPUT
            echo "image_files_paths=$(echo $IMAGE_FILES | paste -sd "," -)" >> $GITHUB_OUTPUT
          fi

  post_problems:
    needs: detect_changes
    if: needs.detect_changes.outputs.problem_files_added == 'true'
    runs-on: self-hosted
    env:
      PROBLEM_FILES_PATHS: ${{ needs.detect_changes.outputs.problem_files_paths }}

    steps:
      - name: Checkout codescript-backend
        uses: actions/checkout@v4
        with:
          repository: jjpark987/codescript-backend
          path: ./codescript-backend
          fetch-depth: 1

      - name: Checkout codescript-problems
        uses: actions/checkout@v4
        with:
          repository: jjpark987/codescript-problems
          path: ./codescript-problems
          fetch-depth: 1
        
      - name: Check workflow dependencies
        env:
          MAC_KEYCHAIN_PASSWORD: ${{ secrets.MAC_KEYCHAIN_PASSWORD }}
        run: |
          echo "🗝️ Unlocking macOS keychain..."
          security -v unlock-keychain -p "${{ secrets.MAC_KEYCHAIN_PASSWORD }}" ~/Library/Keychains/login.keychain-db
          echo "🔍 Checking for codescript_network..."
          docker network inspect codescript_network >/dev/null 2>&1 || docker network create codescript_network
          echo "📄 Added problem files:"
          echo "$PROBLEM_FILES_PATHS"

      - name: Run codescript-backend
        env:
          DOCKER_DATABASE_URL: ${{ secrets.DOCKER_DATABASE_URL }}
        run: |
          echo "🚀 Deploying codescript-backend..."
          cd codescript-backend
          docker compose up -d
          echo "✅ API docker is running!"

      - name: Run codescript-problems
        env:
            DOCKER_API_BASE_URL: ${{ secrets.DOCKER_API_BASE_URL }}
        run: |
          echo "🚀 Deploying codescript-problems..."
          cd codescript-problems
          docker compose up --remove-orphans
          echo "✅ Problems docker has posted all problems!"

      - name: Clean up codescript-backend
        run: |
          echo "🧹 Cleaning up codescript-problems..."
          cd codescript-problems
          docker compose down --remove-orphans
          echo "🧹 Cleaning up codescript-backend..."
          cd .. && cd codescript-backend
          docker compose down --remove-orphans
          echo "✅ Completed clean up!"

  upload_images:
    needs: detect_changes
    if: needs.detect_changes.outputs.image_files_added == 'true'
    runs-on: self-hosted
    env:
      IMAGE_FILES_PATHS: ${{ needs.detect_changes.outputs.image_files_paths }}

    steps:
      - name: Checkout codescript-problems
        uses: actions/checkout@v4
        with:
          repository: jjpark987/codescript-problems
          path: ./codescript-problems
          fetch-depth: 1

      - name: Check IMAGE_FILES_PATHS and install dependencies
        run: |
          echo "📄 Added images:"
          echo "$IMAGE_FILES_PATHS"
          cd codescript-problems
          pip install --no-cache-dir -r requirements.txt
      
      - name: Run upload_images.py
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GC_BUCKET_NAME: ${{ secrets.GC_BUCKET_NAME }}
        run: |
          echo "🖥️ Running script upload_images.py..."
          cd codescript-problems
          python -m python.scripts.db.upload_images --file "$IMAGE_FILES_PATHS"
          echo "✅ Completed script."
