name: Seed Problem(s) and Upload Images

on:
  push:
    paths:
      - 'python/problems/**'
      - 'python/images/**'
    branches:
      - main  

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      problem_files_added: ${{ steps.set-env.outputs.problem_files_added }}
      image_files_added: ${{ steps.set-env.outputs.image_files_added }}
      problem_files_paths: ${{ steps.set-env.outputs.problem_files_paths }}
      image_files_paths: ${{ steps.set-env.outputs.image_files_paths }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Detect Added Files
        id: set-env
        run: |
          echo "Fetching added files in the current repository..."
          ADDED_FILES=$(git diff --name-only --diff-filter=A ${{ github.event.before }} ${{ github.event.after }})

          # Check for problem files
          PROBLEM_FILES=$(echo "$ADDED_FILES" | grep "^python/problems/" || true)
          if [ -n "$PROBLEM_FILES" ]; then
            echo "problem_files_added=true" >> $GITHUB_OUTPUT
            echo "problem_files_paths=$(echo $PROBLEM_FILES | paste -sd "," -)" >> $GITHUB_OUTPUT
          fi

          # Check for image files
          IMAGE_FILES=$(echo "$ADDED_FILES" | grep "^python/images/" || true)
          if [ -n "$IMAGE_FILES" ]; then
            echo "image_files_added=true" >> $GITHUB_OUTPUT
            echo "image_files_paths=$(echo $IMAGE_FILES | paste -sd "," -)" >> $GITHUB_OUTPUT
          fi

  seed_problems:
    needs: detect_changes
    if: needs.detect_changes.outputs.problem_files_added == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A (codescript-backend)
        uses: actions/checkout@v4
        with:
          repository: jjpark987/codescript-backend
          ref: fastapi
          path: ./codescript-backend
          fetch-depth: 1

      - name: Run codescript-problems (Problem Seeder Script)
        run: |
          echo "Seeding problem files..."
          echo "${{ needs.detect_changes.outputs.problem_files_paths }}"

  upload_images:
    needs: detect_changes
    if: needs.detect_changes.outputs.image_files_added == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Upload images to Google Cloud Storage
        run: |
          echo "Uploading images to Google Cloud Storage..."
          echo "${{ needs.detect_changes.outputs.image_files_paths }}"

          # # Install gcloud CLI
          # sudo apt-get update && sudo apt-get install -y google-cloud-sdk
          # echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcp-credentials.json

          # # Authenticate with Google Cloud
          # gcloud auth activate-service-account --key-file=$HOME/gcp-credentials.json
          # gcloud config set project YOUR_PROJECT_ID

          # # Upload images
          # IFS=',' read -ra FILES <<< "${{ needs.detect_changes.outputs.image_files_paths }}"
          # for file in "${FILES[@]}"; do
          #   gsutil cp "$file" gs://YOUR_BUCKET_NAME/images/
          # done